version: '3.9'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nuxt-app
    env_file:
      - .env.production
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nuxt-app
    restart: always
